---
name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  secrets-detection:
    uses: ./.github/workflows/secrets-detection.yml
    with:
      scan-paths: '.'
      fail-on-secrets: true

  lint:
    uses: ./.github/workflows/lint.yml
    with:
      scan-paths: '.'
      fail-on-errors: true

  security:
    uses: ./.github/workflows/security.yml
    with:
      scan-paths: '.'
      fail-on-errors: true
