name: CI Pipeline
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  security-events: write

jobs:
  secrets-detection:
    uses: ./.github/workflows/secrets-detection.yml
    with:
      scan-paths: '.'
      fail-on-secrets: true

  lint:
    uses: KurhyWns/shared-pipeline/.github/workflows/lint.yml@main
    with:
      scan-paths: '.'
      fail-on-errors: true
